platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: spring-vault-broker

run:
  path: mvn
  args: ["-f", "spring-vault-broker/pom.xml","test"]
